class Orchestrator:
    def __init__(self):
        self.agents = []

    def register_agent(self, agent):
        self.agents.append(agent)

    def get_agent(self, agent_name):
        return next(
            (
                agent
                for agent in self.agents
                if agent.name == agent_name
            ),
            None,
        )

    def select_todo_issue(self, issues):
        return next(
            (
                issue
                for issue in issues
                if issue.get("status", "").lower() == "to do"
            ),
            None,
        )

    def run(self, context=None):
        results = {
            agent.name: agent.execute(context)
            for agent in self.agents
        }

        jira_result = results.get("Jira Agent", {})
        jira_issues = jira_result.get("jira", {}).get("issues", [])

        selected_issue = self.select_todo_issue(jira_issues)

        if not selected_issue:
            results["Automation"] = {
                "status": "no_todo_issue",
            }
            return results

        github_agent = self.get_agent("GitHub Agent")

        if github_agent is None:
            results["Automation"] = {
                "status": "github_agent_not_found",
            }
            return results

        branch_name = github_agent.make_branch_name(selected_issue)

        branch_result = github_agent.create_branch(
            branch_name=branch_name,
            source_branch="main",
        )

        issue_key = selected_issue["key"]
        summary = selected_issue["summary"]

        work_plan = f"""# Automated Work Plan

Jira Issue: {issue_key}
Summary: {summary}

## Planned Work

- Review Jira requirements
- Create implementation branch
- Implement requested change
- Run automated tests
- Validate infrastructure configuration
- Create pull request
- Update Jira workflow status

Generated automatically by AI Autonomous DevOps Platform.
"""

        file_result = github_agent.create_or_update_file(
            branch_name=branch_name,
            file_path=f"docs/automation/{issue_key}.md",
            content=work_plan,
            commit_message=f"{issue_key}: add automated implementation plan",
        )

        pr_result = github_agent.create_pull_request(
            branch_name=branch_name,
            title=f"{issue_key}: {summary}",
            body=(
                f"Automated pull request for Jira issue {issue_key}.\n\n"
                f"**Summary:** {summary}\n\n"
                "Generated by the AI Autonomous DevOps Platform."
            ),
            base_branch="main",
        )
        
        jira_agent = self.get_agent("Jira Agent")
        jira_transition = None

        if jira_agent is not None:
            jira_transition = jira_agent.move_issue(
                issue_key,
                "In Progress",
            )

        results["Automation"] = {
            "status": "completed",
            "selected_issue": selected_issue,
            "branch_result": branch_result,
            "file_result": file_result,
            "pull_request": pr_result,
            "jira_transition": jira_transition,
        }

        return results